FROM opensuse:latest
MAINTAINER Axel <apaschoabarres@gmail.com>
LABEL Vendor="OpenSuse image" 

COPY files_installation /playbook

RUN zypper -n update  \ 
  && zypper -n install wget python-pip git

RUN pip install --upgrade pip \
  && pip install ansible

RUN ansible-playbook -i localhost, -c local /playbook/install_inside_container.yaml

ADD ./* /tmp/
